# Generated by Django 4.2.5 on 2023-10-04 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('live_until', models.DateTimeField()),
                ('current_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='default_item.jpg', upload_to='item_pics')),
                ('base_price', models.IntegerField(default=0)),
                ('current_price', models.IntegerField(default=0)),
                ('highest_bidder', models.CharField(default='None', max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
